# Generated by Django 5.0.7 on 2024-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='user',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
