# Generated by Django 5.0.7 on 2024-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_basemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
